<?php

require_once dirname(__FILE__) . '/bootstrap.php';

/**
 * Test class for Symfony_Component_Yaml_Inline.
 * Generated by PHPUnit on 2012-02-24 at 07:54:16.
 */
class Symfony_Component_Yaml_InlineTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var Symfony_Component_Yaml_Inline
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Symfony_Component_Yaml_Inline;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @covers Symfony_Component_Yaml_Inline::parse
	 * @todo Implement testParse().
	 */
	public function testParse()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Symfony_Component_Yaml_Inline::dump
	 * @todo Implement testDump().
	 */
	public function testDump()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Symfony_Component_Yaml_Inline::parseScalar
	 * @todo Implement testParseScalar().
	 */
	public function testParseScalar()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
